### ISSUE TITLE
[Bug]: AM2R Multitroid always building with HQ music

### ISSUE THREAD

**Issue by tharubberchicken** [izzy2fancy/termux-app#3]
### Problem description

Selecting **N** when prompted for HQ music will still build with HQ music regardless. This only occurs when building Multitroid version.

### Steps to reproduce the behavior.

Simply don't choose HQ music and this will occur. Tried with arm64-v8a and universal versions of the builder.

### What is the expected behavior?

Multitroid APK should be built with standard quality music when selecting **N** to HQ music when prompted.

### System information

* Termux application version: 0.118.0+490fe07
* Android OS version: 13
* Device model: Samsung S22+

**Comment by izzy2fancy** [comment]
Ok thanks. I'll look into it.

**Comment by izzy2fancy** [comment]
> ### Problem description
> Selecting **N** when prompted for HQ music will still build with HQ music regardless. This only occurs when building Multitroid version.
> 
> ### Steps to reproduce the behavior.
> Simply don't choose HQ music and this will occur. Tried with arm64-v8a and universal versions of the builder.
> 
> ### What is the expected behavior?
> Multitroid APK should be built with standard quality music when selecting **N** to HQ music when prompted.
> 
> ### System information
> * Termux application version: 0.118.0+490fe07
> * Android OS version: 13
> * Device model: Samsung S22+

Should be fixed now. Try to do it again. No need to update the builder. I fixed it on the repo. Thanks for finding this bug for me!

**Comment by izzy2fancy** [comment]
Fixed. Change the linked zip file on repo. No need to update builder.
